name: tunneling
description: "An app for handling encrypted communications"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.2.4
  usb_serial: ^0.5.2
  wakelock_plus: ^1.3.2
  xmpp_plugin: ^2.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
